export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";


//chat users actions

export const ONLINE_USERS = "ONLINE_USERS";
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_LEFT = "USER_LEFT";


//chat messages actions

export const LATEST_MESSAGES = "LATEST_MESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";

